### ISSUE TITLE
Ненужные файлы

### ISSUE THREAD

**Issue by alexmikhalevich** [qugok/ProjectTPGame2.0#3]
Зачем нужны пустые файлы Avatar.cpp и outputs.cpp?

**Comment by qugok** [comment]
они понадобятся в будущем (Avatar) для отрисовки разных юнитов
outputs действительно рудимент

**Comment by alexmikhalevich** [comment]
ну так если они будут нужны в будущем, зачем они в репозитории уже сейчас?

**Comment by qugok** [comment]
ну
чтобы не забыть

**Comment by alexmikhalevich** [comment]
вообще говоря, так конечно не принято делать
учти это на будущее

как вариант - можно было в мастере держать основную конечную версию, а в деве уже со всеми штуками для "не забыть"
